### PR TITLE
Dirty hack to hopefully fix #219

### LINKED ISSUE #219: New anti-bot "feature"
Kleinanzeigen gets more annoying every month. Now with chrome I get an additional verification request before the login appears.

Screenshot_20231020_180813

Unfortunately even if I solve it in time before the script exits, I only get "Du wurdest gesperrt" ("You have been locked out"). 

Sometimes after a few restarts, the puzzle won't appear but it gets more rare. Strangely I've never seen this in Firefox and it can be solved in a regular chromium browser.

### PR DESCRIPTION
**Pull request by DreckSoft**
*Issue #, if available:*
#219

*Description of changes:*
Use undetected_chromedriver
This is a really quick and ugly hack. It requires selenium to be fixed to 4.12 and some experimental chromedriver options disabled. With this patch you MAY be able to publish something. At least with a working Chromium profile the anti-bot feature did not appear. Strangely login detection did not work, neither did login. If I enter https://www.keinanzeigen.de manually in the URL of the newly launched browser while displaying the login page the second time, it worked. So this will require more work but it is a start. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SphaeroX** [comment]
```
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: EDGE 119.0.2151.97 [C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe]
[ERROR] ConnectionError: Could not reach host. Are you offline?
```

**Review by apeltzer — APPROVED** [review]
Looks good to me and seems to be working for me 👍🏻

**Comment by SphaeroX** [comment]
i still got the error:

```
2023-12-28 15:52:06,471 [INFO] App version: 0.1.dev263+g08bffa8
2023-12-28 15:52:06,471 [WARNING] You provided no ads selector. Defaulting to "new".
2023-12-28 15:52:06,476 [INFO] Loading config from [C:\Users\xxx\OneDrive\Dokumente\kleinanzeigen-bot\config.yaml]...
2023-12-28 15:52:06,497 [INFO]  -> found 145 categories
2023-12-28 15:52:06,498 [INFO] Creating WebDriver session...
2023-12-28 15:52:06,508 [INFO] Using Browser: EDGE 120.0.2210.91 [C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe]
2023-12-28 15:52:08,236 [ERROR] ConnectionError: Could not reach host. Are you offline?

```

**Comment by apeltzer** [comment]
Did you install as @DreckSoft suggested from _his_ fork using pdm?

**Comment by SphaeroX** [comment]
@apeltzer u mean that one?
```
pip install pdm
pdm install
```

yes i did it

**Comment by apeltzer** [comment]
I used chrome 🤷‍♂️ with separate profile

**Comment by euberdeveloper** [comment]
In case it won't be merged or it will not work, you can try like in @259

**Comment by sebthom** [comment]
Latest release does not use selenium anymore

**Pull request closed without merging**
