### PR TITLE
ADD download --all feature

### PR DESCRIPTION
**Pull request by PhilK-7**
*Implement #131 *

*Description of changes:*
Supply the `--all` flag to download all of the ads on your profile. The feature browses and scrolls the ad section on your profile. It supports multiple ad overview pages, if you have more than 25 ads. This has been tested with 0-50 ads. The references to your ads are captured, and the 'download ad' feature used on them.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sebthom** [comment]
Do you think we could streamline the parameters to select the ads? So for publishing we use `--ads=all|new|due`, could we use `--ads=all|new|<id1>,<id2>,...` for the download command instead of having the new `--all` and `--ad <id>` options?

**Comment by PhilK-7** [comment]
I agree, it makes sense to keep the parameters consistent.

**Comment by sebthom** [comment]
LGTM. Is this ready to be merged?

**Comment by PhilK-7** [comment]
I'd guess so

**Comment by sebthom** [comment]
Thanks!

**Pull request merged**
