### PR TITLE
Allow specific ids to publish command with --ads option

### PR DESCRIPTION
**Pull request by Heavenfighter**
#177 

Allows specific ids for the publish command with --ads option.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sebthom** [comment]
LGTM. Is your PR ready to be merged?

**Comment by Heavenfighter** [comment]
thank you, yes its ready

**Comment by sebthom** [comment]
Thank you!!

**Comment by Heavenfighter** [comment]
Yes you're right. I'll fix it.

**Pull request merged**
