### PR TITLE
set address visibility field per setting

### PR DESCRIPTION
**Pull request by DenisLanz**
*Issue #, if available:*
#74 #75 
*Description of changes:*
added a setting for address visibility and set the checkmark accordingly to enable the street input field

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sebthom** [comment]
How about instead of adding a new configuration option use something like this?
```python
        #############################
        # set contact street
        #############################
        if ad_cfg["contact"]["street"]:
            try:
                self.webdriver.find_element(By.ID, "addressVisibility").click()
                pause(2000)
            except NoSuchElementException:
                # ignore
                pass
            self.web_input(By.ID, "pstad-street", ad_cfg["contact"]["street"])
```

**Comment by DenisLanz** [comment]
You mean make it implicit, if a street is configured to check the adressVisibility? Would that allow the user to configure that on a per ad basis if there is a street in the default configuration?

**Comment by sebthom** [comment]
If they explicitly set the street to an empty value yes

**Comment by DenisLanz** [comment]
Alright. Now I just need to figure out how I can update a pull request. 😄

**Comment by DenisLanz** [comment]
Used and tested your code, worked well and I could publish an ad. Learned a lot with my first contribution to a public repository and python, thanks.

**Comment by sebthom** [comment]
Can you try if it works like this too?

```python
        if ad_cfg["contact"]["street"]:
                try:
                    if not self.webdriver.find_element(By.ID, "pstad-street").is_enabled():
                        self.webdriver.find_element(By.ID, "addressVisibility").click()
                        pause(2000)
                except NoSuchElementException:
                    # ignore
                    pass
            self.web_input(By.ID, "pstad-street", ad_cfg["contact"]["street"])
```

**Comment by DenisLanz** [comment]
pushed before testing… 🙄 need to fix something first

**Comment by DenisLanz** [comment]
Fixed and tested it. Stumbled over another unrelated issues though

```
Message: Element xpath='//meta[@name='_csrf']' not found
```

went away on the second attempt.

**Comment by sebthom** [comment]
I think now I screwed up trying to resolve the merge conflict. :-/

**Comment by DenisLanz** [comment]
Like so?

**Pull request merged**
