### PR TITLE
Fix for error #353 and #351

### PR DESCRIPTION
**Pull request by Heavenfighter**
*Issue #, if available:*
#353 

*Description of changes:*
changed css selector

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Heavenfighter** [comment]
#351
The order has to be changed when checking for element and deleting old ad

**Comment by DreckSoft** [comment]
After applying your patch, the old ad does no longer get deleted when re-publishing.

**Comment by Heavenfighter** [comment]
Hmm thats strange, i have no problems when republishing ads. The old are deleted.

**Review by IchSkill — APPROVED** [review]

**Review by thetomatoplanet — APPROVED** [review]

**Comment by sebthom** [comment]
Thanks!

**Pull request merged**
